# Javascript Node CircleCI 2.1 configuration file
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3
jobs:
  build:
    working_directory: ~/natours
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-site-script-file
          command: 'npm run build:js'
  deploy:
    docker:
      - image: circleci/buildpack-deps:trusty
    steps:
      machine:
              enabled: true
          working_directory: ~/natours
          environment:
            HEROKU_APP: "sleepy-refuge-55486" # define env var $HEROKU_APP
          steps:
            - checkout
            - run:
                name: Setup Heroku
                command: bash .circleci/setup-heroku.sh # run a script to set up Heroku

            - run:
                command: |
                  git push heroku sequential-branch-filter:master
                  heroku run rake db:migrate
                  sleep 5 # sleep for 5 seconds to wait for dynos
                  heroku restart
##    - run:
##        name: Deploy on Heroku Login
##        command: heroku login
##        command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
